/* eslint-disable no-unused-vars */
import React from "react";
// css
import "./section7.css";
import { NavHashLink } from "react-router-hash-link";
function Section7() {
  return (
    <>
      {/* secton top  */}
      <div className="purple-red-circle-bg mt-10">
        <div className="mx-4 pt-[30%]">
          <span className="text-[32px] leading-[34px] font-light faded-pink-secondary ">
            Secure the Network.
            <br /> Earn $NYT.
          </span>
        </div>
      </div>
      {/* section bottom  */}
      <div className="mx-4">
        <div className="grid grid-cols-12 mt-[19px]">
          <div
            className="col-span-12"
            style={{ opacity: 1, transform: "none" }}>
            <div className="col-span-12 relative">
              <div className="planet-bg relative h-[342px] sm:h-[500px]">
                <div className="absolute top-[55%] sm:top-[65%]">
                  <div className="flex items-center">
                    <div className="h-[24px] rotate-[24.5deg] border-r-2 border-[#7c7c7c] w-1 mr-2"></div>
                    <div className="h-[24px] rotate-[24.5deg] mr-8 lg:mr-32 border-r-2 border-[#7c7c7c] w-1"></div>
                    <span className="text-[36px] leading-[36px] tracking-[-2%] font-light text-white">
                      Decentralized
                    </span>
                  </div>
                  <span className="text-[36px] leading-[36px] tracking-[-2%] font-light text-white">
                    Digital Health
                    <span className="faded-purple line-clamp-1">Platform</span>
                  </span>
                </div>
              </div>
            </div>
          </div>
          <div className="col-span-12 grid grid-cols-5 mt-4">
            <div className="col-span-5">
              <span className="text-[20px] text-white leading-[24px] font-light text-left">
                Comprehensive.
              </span>
              <span className="text-[20px] text-white leading-[24px] font-light text-left">
                Verified.
              </span>
              <span className="text-[20px] text-white leading-[24px] font-light text-left">
                Accessible.
              </span>
              <p className="leading-[22px] text-justify font-light text-[#FCFCFC] opacity-50 mt-6">
                The DDH Platform provides access to a diverse range of verified
                and validated data categories; including health, environmental,
                AI, and nutritional data. All data is generated by verified
                users of all demographics wearing NYT-compatible IoT Devices.
              </p>
              <div className="flex flex-col items-center gap-y-4">
                <div className="border border-white/25 w-full mt-[40px]"></div>
                <span className="text-[80px] leading-[27px] font-normal faded-tangerine py-8">
                  45TB
                </span>
                <p className="leading-[21px] text-[#FCFCFC] opacity-50">
                  Total Data Gathered Since Genesis
                </p>
                <NavHashLink
                  className="w-full"
                  to="/get-started-vsc#ddh-platform">
                  <button className="border-faded-pink mt-8 py-4 w-full flex justify-center items-center hover:border-faded-pink-pressed">
                    <span className="text-white">Learn More</span>
                    <img
                      alt="Arrow right"
                      loading="lazy"
                      width="4"
                      height="8"
                      decoding="async"
                      data-nimg="1"
                      className="ml-4"
                      src="https://www.vyvo.com/shapes/arrow-right.svg"
                      style={{
                        color: "transparent",
                        objectFit: "contain",
                        objectPosition: "left center",
                      }}
                    />
                  </button>
                </NavHashLink>
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}

export default Section7;
